language: cpp
compiler:
- gcc
#- clang

env:
    - GCC_VERSION="4.9"
    - GCC_VERSION="4.8"

before_install:
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
    - sudo apt-get update -qq
    - sudo apt-get install libasound2-dev
    - sudo apt-get install libfreetype6-dev
    - sudo ln -s /usr/include/freetype2/freetype /usr/include/freetype

    - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-${GCC_VERSION}; fi
    - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq gcc-${GCC_VERSION}; fi
    - if [ "$CXX" == "g++" ]; then sudo ln -s -v -f $(which g++-${GCC_VERSION}) /usr/bin/g++; fi
    - if [ "$CXX" == "g++" ]; then sudo ln -s -v -f $(which gcc-${GCC_VERSION}) /usr/bin/gcc; fi

    - if [ "$LIBCXX" == "true" ]; then cwd=$(pwd); fi
    - if [ "$LIBCXX" == "true" ]; then export CXXFLAGS="-std=c++0x -stdlib=libc++"; fi
    - if [ "$LIBCXX" == "true" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx; fi
    - if [ "$LIBCXX" == "true" ]; then cd libcxx/lib && bash buildit; fi
    - if [ "$LIBCXX" == "true" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
    - if [ "$LIBCXX" == "true" ]; then sudo mkdir /usr/include/c++/v1; fi
    - if [ "$LIBCXX" == "true" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
    - if [ "$LIBCXX" == "true" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
    - if [ "$LIBCXX" == "true" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi
    - if [ "$LIBCXX" == "true" ]; then CXX_FLAGS="${CXX_FLAGS} -stdlib=libc++ -I/usr/include/c++/v1/"; fi
    - if [ "$LIBCXX" == "true" ]; then CXX_LINKER_FLAGS="${CXX_LINKER_FLAGS} -stdlib=libc++ -L/usr/lib/ -lc++"; fi

install:
    - wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
    - bii setup:cpp
    - $CXX --version

script:
    - bii init -l simple
    - bii find --update
    - bii configure
    - bii build